let responseListaOperacao = [
    {
      "textoLinhaCredito": " BB Crédito Consignação",
      "codigoEstadoAtualContrato": 2,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100157152,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "Estamos confirmando sua margem",
      "horarioEstadoEtapaLinhaCredito": "10:13:45",
      "numeroConvenio": 16936,
      "textoDescricaoEtapaLinhaCreditoLegado": "Estamos confirmando sua margem junto ao seu empregador. Se o seu empregador solicitar comandos adicionais (ex. carta margem) procure a agência!",
      "dataEstadoEtapaLinhaCredito": "04.10.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Pendente de Confirmacao",
      "textoTipoEtapaLinhaCredito": "Verificação do Empregador",
      "opcaoParcela": 1,
      "codigoLinhaCredito": 2882,
      "dataOperacaoCreditoDiretoAoConsumidor": "04.10.2022",
      "nomeLinhaCredito": "BB Crédito Consignado",
      "codigoTipoEtapaLinhaCredito": 40,
      "nomeConvenio": "Padaria Dantas Cornetto",
      "codigoEstadoEtapaLinhaCredito": 1,
      "valorSolicitacao": "3.000,00",
      "dataTratada": "20221004",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "04/10/2022",
      "textoLinhaCreditoFitrado": " BB Crédito Consignação",
      "opcao": 1
    },
    {
      "textoLinhaCredito": "CDC Fgts Saque Aniversario",
      "codigoEstadoAtualContrato": 40,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100153865,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[\"12.10.2022\"],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_confirmarproposta\"}",
      "horarioEstadoEtapaLinhaCredito": "12:12:55",
      "numeroConvenio": 0,
      "textoDescricaoEtapaLinhaCreditoLegado": "Você precisa confirmar o registro da sua operação até 12.10.2022! Acesse a opção \"Confirmações Pendentes\" nos terminais BB, internet ou celular",
      "dataEstadoEtapaLinhaCredito": "03.10.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Pendente Conformidade",
      "textoTipoEtapaLinhaCredito": "Aceite do Cliente",
      "opcaoParcela": 2,
      "codigoLinhaCredito": 2097,
      "dataOperacaoCreditoDiretoAoConsumidor": "03.10.2022",
      "nomeLinhaCredito": "CDC Fgts Saque Aniversario",
      "codigoTipoEtapaLinhaCredito": 30,
      "nomeConvenio": "",
      "codigoEstadoEtapaLinhaCredito": 1,
      "valorSolicitacao": "848,11",
      "dataTratada": "20221003",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "03/10/2022",
      "textoLinhaCreditoFitrado": "CDC Fgts Saque Aniversa",
      "opcao": 2
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 10,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100158094,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "Uhuuul! O dinheiro já está na sua conta \\ud83c\\udf89",
      "horarioEstadoEtapaLinhaCredito": "10:52:04",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Seu crédito já está disponível na sua conta!",
      "dataEstadoEtapaLinhaCredito": "26.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Contrato Normal",
      "textoTipoEtapaLinhaCredito": "Liberação",
      "opcaoParcela": 3,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "26.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 60,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 2,
      "valorSolicitacao": "1.000,00",
      "dataTratada": "20220926",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "26/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 3
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 10,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100158093,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "Uhuuul! O dinheiro já está na sua conta \\ud83c\\udf89",
      "horarioEstadoEtapaLinhaCredito": "10:29:04",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Seu crédito já está disponível na sua conta!",
      "dataEstadoEtapaLinhaCredito": "26.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Contrato Normal",
      "textoTipoEtapaLinhaCredito": "Liberação",
      "opcaoParcela": 4,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "26.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 60,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 2,
      "valorSolicitacao": "1.000,00",
      "dataTratada": "20220926",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "26/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 4
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 99,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100157613,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "10:20:00",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Operação cancelada em 22.09.2022",
      "dataEstadoEtapaLinhaCredito": "22.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Contrato Cancelado",
      "textoTipoEtapaLinhaCredito": "Liberação",
      "opcaoParcela": 5,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "22.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 60,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "1.073,67",
      "dataTratada": "20220922",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "22/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 5
    },
    {
      "textoLinhaCredito": "BB Crédito Automático",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100151719,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:22",
      "numeroConvenio": 0,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 6,
      "codigoLinhaCredito": 2997,
      "dataOperacaoCreditoDiretoAoConsumidor": "08.09.2022",
      "nomeLinhaCredito": "CDC Automatico",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "201,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "08/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Automático",
      "opcao": 6
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100151718,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:22",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 7,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "08.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "1.000,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "08/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 7
    },
    {
      "textoLinhaCredito": "BB Crédito Automático",
      "codigoEstadoAtualContrato": 10,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100151209,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "Uhuuul! O dinheiro já está na sua conta \\ud83c\\udf89",
      "horarioEstadoEtapaLinhaCredito": "08:31:03",
      "numeroConvenio": 0,
      "textoDescricaoEtapaLinhaCreditoLegado": "Seu crédito já está disponível na sua conta!",
      "dataEstadoEtapaLinhaCredito": "06.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Contrato Normal",
      "textoTipoEtapaLinhaCredito": "Liberação",
      "opcaoParcela": 8,
      "codigoLinhaCredito": 2997,
      "dataOperacaoCreditoDiretoAoConsumidor": "06.09.2022",
      "nomeLinhaCredito": "CDC Automatico",
      "codigoTipoEtapaLinhaCredito": 60,
      "nomeConvenio": "",
      "codigoEstadoEtapaLinhaCredito": 2,
      "valorSolicitacao": "2.000,00",
      "dataTratada": "20220906",
      "opcao": 8
    },
    {
      "textoLinhaCredito": "BB Créd. 13º Salário",
      "codigoEstadoAtualContrato": 10,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100151208,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "Uhuuul! O dinheiro já está na sua conta \\ud83c\\udf89",
      "horarioEstadoEtapaLinhaCredito": "08:01:12",
      "numeroConvenio": 16936,
      "textoDescricaoEtapaLinhaCreditoLegado": "Seu crédito já está disponível na sua conta!",
      "dataEstadoEtapaLinhaCredito": "06.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Contrato Normal",
      "textoTipoEtapaLinhaCredito": "Liberação",
      "opcaoParcela": 9,
      "codigoLinhaCredito": 3100,
      "dataOperacaoCreditoDiretoAoConsumidor": "06.09.2022",
      "nomeLinhaCredito": "BB Créd. 13º Salário",
      "codigoTipoEtapaLinhaCredito": 60,
      "nomeConvenio": "Padaria Dantas Cornetto",
      "codigoEstadoEtapaLinhaCredito": 2,
      "valorSolicitacao": "2.247,44",
      "dataTratada": "20220906",
      "opcao": 9
    },
    {
      "textoLinhaCredito": "BB Crédito Renovação",
      "codigoEstadoAtualContrato": 40,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100150897,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[\"14.09.2022\"],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_confirmarproposta\"}",
      "horarioEstadoEtapaLinhaCredito": "12:34:37",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Você precisa confirmar o registro da sua operação até 14.09.2022! Acesse a opção \"Confirmações Pendentes\" nos terminais BB, internet ou celular",
      "dataEstadoEtapaLinhaCredito": "05.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Pendente Conformidade",
      "textoTipoEtapaLinhaCredito": "Aceite do Cliente",
      "opcaoParcela": 10,
      "codigoLinhaCredito": 2996,
      "dataOperacaoCreditoDiretoAoConsumidor": "05.09.2022",
      "nomeLinhaCredito": "BB Crédito Renovação",
      "codigoTipoEtapaLinhaCredito": 30,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 1,
      "valorSolicitacao": "4.697,61",
      "dataTratada": "20220905",
      "opcao": 10
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100150878,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 11,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "02.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "108,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "02/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 11
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100150877,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 12,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "02.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "113,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "02/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 12
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100150876,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 13,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "02.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "105,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "02/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 13
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100150040,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 14,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "02.09.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "100,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "02/09/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 14
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100144756,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "11:45:52",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Cancelada para contratação com novas condições.",
      "dataEstadoEtapaLinhaCredito": "30.08.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 15,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "29.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "402,00",
      "dataTratada": "20220830",
      "opcao": 15
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100144755,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "11:43:38",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Cancelada para contratação com novas condições.",
      "dataEstadoEtapaLinhaCredito": "30.08.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 16,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "29.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "401,00",
      "dataTratada": "20220830",
      "opcao": 16
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100144581,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 17,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "25.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "2.004,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "25/08/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 17
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100139890,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 18,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "12.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "500,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "12/08/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 18
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100139879,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 19,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "12.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "500,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "12/08/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Salário",
      "opcao": 19
    },
    {
      "textoLinhaCredito": "BB Créd. 13º Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100138104,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "10:10:14",
      "numeroConvenio": 16936,
      "textoDescricaoEtapaLinhaCreditoLegado": "Cancelada para contratação com novas condições.",
      "dataEstadoEtapaLinhaCredito": "12.08.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 20,
      "codigoLinhaCredito": 3100,
      "dataOperacaoCreditoDiretoAoConsumidor": "12.08.2022",
      "nomeLinhaCredito": "BB Créd. 13º Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Padaria Dantas Cornetto",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "2.100,00",
      "dataTratada": "20220812",
      "opcao": 20
    },
    {
      "textoLinhaCredito": "BB Crédito Automático",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100138075,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 0,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 21,
      "codigoLinhaCredito": 2997,
      "dataOperacaoCreditoDiretoAoConsumidor": "11.08.2022",
      "nomeLinhaCredito": "CDC Automatico",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "503,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "11/08/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Automático",
      "opcao": 21
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100138063,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "15:36:51",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Cancelada para contratação com novas condições.",
      "dataEstadoEtapaLinhaCredito": "11.08.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 22,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "11.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "530,00",
      "dataTratada": "20220811",
      "opcao": 22
    },
    {
      "textoLinhaCredito": "BB Crédito Automático",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100137992,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "08:43:21",
      "numeroConvenio": 0,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta foi cancelada porque você deixou de confirmá-la no menu Confirmações Pendentes. Caso deseje, contrate uma nova proposta no menu Empréstimos.",
      "dataEstadoEtapaLinhaCredito": "29.09.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 23,
      "codigoLinhaCredito": 2997,
      "dataOperacaoCreditoDiretoAoConsumidor": "11.08.2022",
      "nomeLinhaCredito": "CDC Automatico",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "503,00",
      "dataTratada": "20220929",
      "dataOperacaoCreditoDiretoAoConsumidorTratada": "11/08/2022",
      "textoLinhaCreditoFitrado": "BB Crédito Automático",
      "opcao": 23
    },
    {
      "textoLinhaCredito": "BB Créd. 13º Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100137972,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "15:36:29",
      "numeroConvenio": 16936,
      "textoDescricaoEtapaLinhaCreditoLegado": "Cancelada para contratação com novas condições.",
      "dataEstadoEtapaLinhaCredito": "11.08.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 24,
      "codigoLinhaCredito": 3100,
      "dataOperacaoCreditoDiretoAoConsumidor": "11.08.2022",
      "nomeLinhaCredito": "BB Créd. 13º Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Padaria Dantas Cornetto",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "2.100,00",
      "dataTratada": "20220811",
      "opcao": 24
    },
    {
      "textoLinhaCredito": "BB Crédito Salário",
      "codigoEstadoAtualContrato": 9,
      "textoTipoLiberacaoCredito": "CONTA CORRENTE",
      "numeroContratoOperacao": 100135120,
      "textoDescricaoEtapaLinhaCreditoTraduzido": "{\"params\":{\"header\":[],\"body\":[],\"footer\":[]},\"idTipoComponente\":5,\"nomeTipoComponente\":\"Template WhatsApp\",\"id\":\"botao_novapropostacdc\"}",
      "horarioEstadoEtapaLinhaCredito": "14:57:36",
      "numeroConvenio": 330382,
      "textoDescricaoEtapaLinhaCreditoLegado": "Proposta cancelada",
      "dataEstadoEtapaLinhaCredito": "09.08.2022",
      "codigoTipoLiberacaoCredito": 1,
      "textoEstadoAtualContrato": "Proposta Cancelada",
      "textoTipoEtapaLinhaCredito": "Acolhimento",
      "opcaoParcela": 25,
      "codigoLinhaCredito": 2991,
      "dataOperacaoCreditoDiretoAoConsumidor": "09.08.2022",
      "nomeLinhaCredito": "BB Crédito Salário",
      "codigoTipoEtapaLinhaCredito": 10,
      "nomeConvenio": "Mercadinho Salario Teste",
      "codigoEstadoEtapaLinhaCredito": 9,
      "valorSolicitacao": "356,00",
      "dataTratada": "20220809",
      "opcao": 25
    }
  ],